---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: rpi-lab
prometheusSpec:
  interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: n8n
      version: 1.*
      sourceRef:
        kind: OCIRepository
        name: n8n
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: n8n.int.draugelis.dev
      tls:
        - hosts:
            - n8n.int.draugelis.dev
          secretName: star-prod-tls
