---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: rpi-lab
spec:
  interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: n8n
      version: 1.*
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      className: traefik
      hosts:
        - host: n8n.int.draugelis.dev
          paths: []
      tls:
        - hosts:
            - n8n.int.draugelis.dev
          secretName: star-prod-tls
