---
apiVersion: v1
kind: Service
metadata:
  name: capacitor-service
  namespace: flux-system
spec:
  type: NodePort
  ports:
    - nodePort: 9000
      port: 9000
      targetPort: 9000
  selector:
    matchLabels:
      app.kubernetes.io/instance: capacitor