---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: traefik
      version: 31.1.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 12h

  install:
    crds: CreateReplace
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3

  # Traefik Values - https://github.com/traefik/traefik-helm-chart/blob/v31.1.1/traefik/values.yaml
  values:
    image:
      tag: 3.3.4

    core:
      defaultRuleSyntax: v2

    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"

    service:
      enabled: true
      single: true
      type: LoadBalancer

    ingressClass:
      enabled: true
      isDefaultClass: true

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1

    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
        allowEmptyServices: false
        namespaces: []

      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowEmptyServices: false
        namespaces: []
        publishedService:
          enabled: false

    globalArguments:
      - --global.sendanonymoususage=false

    logs:
      general:
        format: json
        # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
        level: INFO
      access:
        enabled: true
        format: json
        filters: {}
        # -- Enables accessLogs for internal resources. Default: false.
        addInternals: false
