---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
      version: 0.38.3
  values:
    fullnameOverride: victoriametrics-stack
    victoria-metrics-operator:
      enabled: false
    defaultDashboards:
      dashboards:
        victoriametrics-operator:
          enabled: false
    vmsingle:
      spec:
        retentionPeriod: 1w
        resources:
          requests:
            storage: 8Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - vmsingle.int.draugelis.dev
        tls:
          - secretName: star-prod-tls
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - grafana.int.draugelis.dev
        tls:
          - secretName: star-prod-tls

