---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-prod
  namespace: certificates
spec:
  secretName: star-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.int.draugelis.dev"
  dnsNames:
  - "int.draugelis.dev"
  - "*.int.draugelis.dev"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "rpi-lab,capacitor"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "rpi-lab,capacitor"