---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 12h
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    semver: ">=1.0.0"
