---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: n8n
  namespace: flux-system
spec:
  type: oci
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    semver: ">=1.0.0"